version: "3.6"

services:
  wp:
    image: wordpress:latest
    volumes:
      - ./naha-waraba-theme:/var/www/html/wp-content/themes/naha-waraba-theme
      - ./Docker/php.ini:/usr/local/etc/php/php.ini
    environment:
      - WORDPRESS_DB_NAME=wp-db
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=user
      - WORDPRESS_DB_PASSWORD=pass
    depends_on:
      - db
    restart: always
    ports:
      - 8080:80

  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
      - MYSQL_DATABASE=wp-db
    restart: always

volumes:
  db: